name: ciofs-skill-assessment
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Required for full project functionality (dont remove)
  - pytest=8.3.2
  - cmocean=4.0.3
  - fastparquet=2024.2.0
  - ffmpeg=7.1.0
  - geoviews=1.12.0
  - h5netcdf=1.3.0
  - hvplot=0.10.0
  - intake-erddap=0.5.2
  - jupytext=1.16.4
  - kerchunk=0.2.5
  - matplotlib-base=3.9.1
  - oceans=1.1.4
  - ocean-model-skill-assessor=1.3.2
  - pandas=2.2.2
  - pip
  - report-utils=0.1.0
  - seaborn=0.13.2
  - xesmf=0.8.7
  - xroms=0.6.1
  - pip:
    - myst-nb==1.1.1
    - intake-coops==0.4.0
    # - noaa_coops>=0.3.2
    - git+https://github.com/kthyng/noaa_coops.git@toml
  #   - geopy
  #   - git+https://github.com/intake/intake.git
    - git+https://github.com/axiom-data-science/cook-inlet-catalogs.git
    - git+https://github.com/moflaher/ttide_py.git
