name: ciofs-skill-assessment
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Required for full project functionality (dont remove)
  - pytest
  - cmocean
  - ffmpeg
  - geoviews
  - h5netcdf
  - hvplot
  - intake-erddap
  - jupytext
  # - jupyter
  # - jupyter-book
  - kerchunk
  - matplotlib-base
  - oceans
  - ocean-model-skill-assessor
  - fastparquet
  - pandas
  - pip
  - report-utils
  - seaborn
  - xesmf
  - xroms
  - pip:
    - myst-nb
    - intake-coops
    # - noaa_coops>=0.3.2
    - git+https://github.com/kthyng/noaa_coops.git@toml
  #   - geopy
  #   - git+https://github.com/intake/intake.git
    - git+https://github.com/axiom-data-science/cook-inlet-catalogs.git
    - git+https://github.com/moflaher/ttide_py.git
