bias:
  long_name: Bias or MSD
  name: Bias
  value: -0.7612888561463557
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.6604957227465496
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 10.426317209033796
  - 7.75117459538098
  - 9.416062223304204
  - 0.6924587108729071
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 11.743648922604992
  - 8.758032025465134
  - 10.177151194763516
  - 0.6532714087763549
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.6344043606356662
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.3086273351585977
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.5555423792642625
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 0.9424372752058018
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.8276088666719399
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: -1.0809250346647854
