bias:
  long_name: Bias or MSD
  name: Bias
  value: -0.7537293872621469
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.6183436682318254
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 10.484563859303792
  - 7.516547679901123
  - 9.392111082782682
  - 0.7222340771052701
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 12.0616
  - 8.3482
  - 10.14584047004483
  - 0.7385792126298247
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.6434914293766225
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.40743880564144913
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.6383093338197783
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 0.9876977244400335
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.808926040782496
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: -0.7883558756694478
